use_frameworks!
platform :ios, '8.0'

target 'AMKCategories_Example' do
    # 当前工程
    pod 'AMKCategories', :path => '../'
    pod 'AMKCategories/Foundation/NSBundle/GitCommitInfo', :path => '../'
    
    # 第三方
    pod 'AMKLocaleDescription'
    target 'AMKCategories_Tests' do
      inherit! :search_paths
    end
end
