use_frameworks!
platform :ios, '8.0'

target 'AMKCategories_Example' do
    # 当前工程
    pod 'AMKCategories', :path => '../'
    pod 'AMKCategories/UIKit', :path => '../'
    pod 'AMKCategories/Foundation', :path => '../'
    
    # 第三方

    target 'AMKCategories_Tests' do
      inherit! :search_paths
    end
end
